### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/users" 
  REDIS_URL: "redis://redis:6379"